In [1]:
import pandas as pd

# Load CSV
df = pd.read_csv('mimic_cohort.csv')

# Save as Parquet
df.to_parquet('mimic_cohort.parquet')

In [2]:
mimic_cohort = pd.read_parquet('mimic_cohort.parquet')
mimic_cohort.head()

,subject_id,gender,dob,hadm_id,admittime,dischtime,ethnicity,admission_type,insurance,diagnosis,hospital_expire_flag,icustay_id,intime,outtime,first_careunit,last_careunit,los
0,268,F,2132-02-21 00:00:00,110404,2198-02-11 13:40:00,2198-02-18 03:55:00,HISPANIC OR LATINO,EMERGENCY,Medicare,DYSPNEA,1,280836,2198-02-14 23:27:38,2198-02-18 05:26:11,MICU,MICU,3.2490
1,269,M,2130-09-30 00:00:00,106296,2170-11-05 11:04:00,2170-11-27 18:00:00,WHITE,EMERGENCY,Medicaid,SEPSIS;PILONIDAL ABSCESS,0,206613,2170-11-05 11:05:29,2170-11-08 17:46:57,MICU,MICU,3.2788
2,270,M,2048-05-26 00:00:00,188028,2128-06-23 18:26:00,2128-06-27 12:31:00,UNKNOWN/NOT SPECIFIED,ELECTIVE,Medicare,CAROTID STENOSIS\CAROTID ANGIOGRAM AND STENT,0,220345,2128-06-24 15:05:20,2128-06-27 12:32:29,CCU,CCU,2.8939
3,271,F,2074-11-30 00:00:00,173727,2120-08-07 18:56:00,2120-08-20 16:00:00,PATIENT DECLINED TO ANSWER,EMERGENCY,Private,GALLSTONE PANCREATITIS,0,249196,2120-08-07 23:12:42,2120-08-10 00:39:04,MICU,SICU,2.0600
4,272,M,2119-11-21 00:00:00,164716,2186-12-25 21:06:00,2187-01-02 14:57:00,WHITE,EMERGENCY,Medicare,PULMONARY EMBOLIS,0,210407,2186-12-25 21:08:04,2186-12-27 12:01:13,CCU,CCU,1.6202

In [3]:
one_df = pd.read_csv("elixhauser_onehot.csv")

df.to_parquet("elixhauser_onehot.parquet")

In [4]:
onehot_cohort = pd.read_parquet("elixhauser_onehot.parquet")
onehot_cohort.head()

,subject_id,gender,dob,hadm_id,admittime,dischtime,ethnicity,admission_type,insurance,diagnosis,hospital_expire_flag,icustay_id,intime,outtime,first_careunit,last_careunit,los
0,268,F,2132-02-21 00:00:00,110404,2198-02-11 13:40:00,2198-02-18 03:55:00,HISPANIC OR LATINO,EMERGENCY,Medicare,DYSPNEA,1,280836,2198-02-14 23:27:38,2198-02-18 05:26:11,MICU,MICU,3.2490
1,269,M,2130-09-30 00:00:00,106296,2170-11-05 11:04:00,2170-11-27 18:00:00,WHITE,EMERGENCY,Medicaid,SEPSIS;PILONIDAL ABSCESS,0,206613,2170-11-05 11:05:29,2170-11-08 17:46:57,MICU,MICU,3.2788
2,270,M,2048-05-26 00:00:00,188028,2128-06-23 18:26:00,2128-06-27 12:31:00,UNKNOWN/NOT SPECIFIED,ELECTIVE,Medicare,CAROTID STENOSIS\CAROTID ANGIOGRAM AND STENT,0,220345,2128-06-24 15:05:20,2128-06-27 12:32:29,CCU,CCU,2.8939
3,271,F,2074-11-30 00:00:00,173727,2120-08-07 18:56:00,2120-08-20 16:00:00,PATIENT DECLINED TO ANSWER,EMERGENCY,Private,GALLSTONE PANCREATITIS,0,249196,2120-08-07 23:12:42,2120-08-10 00:39:04,MICU,SICU,2.0600
4,272,M,2119-11-21 00:00:00,164716,2186-12-25 21:06:00,2187-01-02 14:57:00,WHITE,EMERGENCY,Medicare,PULMONARY EMBOLIS,0,210407,2186-12-25 21:08:04,2186-12-27 12:01:13,CCU,CCU,1.6202